### ISSUE TITLE
Need a more fluid way to add pokemon while using app

### ISSUE THREAD

**Issue by meredori** [mksanderson/pokeswarm#12]
I had to stop walking once I tapped a pokemon on my app to catch so that I didn't end up walking too far away by the time I caught the pokemon and giving inaccurate data. Possibly look into a way of quickly tagging a location first then adding the pokemon after or integrating with something like a smartwatch or a gesture (would probably require an app as opposed to a website).

**Comment by mksanderson** [comment]
As we discussed it's a bit tricky with permissions access to various aspects of the phone. I'll close this in favour of "making it more fluid" by improving the submission system.
