### ISSUE TITLE
Spacing of Pokemon

### ISSUE THREAD

**Issue by meredori** [mksanderson/pokeswarm#13]
If multiple pokemon are caught at the same spawn spot and your gps doesn't move it results in stacking which makes it impossible to actually see the pokemone caught in that spot.

![image](https://cloud.githubusercontent.com/assets/2755880/17385433/095c8278-5a26-11e6-9884-c8ab8b8caa93.png)

**Comment by mksanderson** [comment]
https://github.com/jawj/OverlappingMarkerSpiderfier Going to look at using something like spiderfier to make it possible to "click" out the positions and see each one within a close radius
