### ISSUE TITLE
Location should be confirmed if different from the screen

### ISSUE THREAD

**Issue by meredori** [mksanderson/pokeswarm#14]
If when I click to add a pokemon and have moved since the last time i focused the map, there should be a dialog telling me that my current location is different to the location on the map.

**Comment by mksanderson** [comment]
What do you think of this:
- Now when you open the form each time, your location is being checked and updated, you can then drag the marker around to where you want it
- I haven't added a notification telling you that your location is different, but I have included an update location button

The reason for these is that I'm hoping to make it so it's quite easy to add things at a later time if you forgot to while logging them and if you're in a car doing that, it could be quite annoying to keep getting notified? I could look into adding something non obtrusive like the update location button becomes prominent and suggests you might want to use it?
