### ISSUE TITLE
Map won't load on mobile half the time

### ISSUE THREAD

**Issue by Bribabri** [mksanderson/pokeswarm#17]
Sometimes the map won't load no matter how many times I press refresh. Sometimes closing the app and opening helps but sometimes just won't load at all

**Comment by mksanderson** [comment]
Is this only when it is saved on your home screen or when you open a browser and go to the URL?

**Comment by mksanderson** [comment]
Yeah, so I have seen this as well and seems to only be when the map is saved to homescreen. I've made a change to the way the external dependencies (for google maps) are loaded in the latest release that will hopefully fix it. Let me know if it's still occuring

**Comment by mksanderson** [comment]
Tested in various situations and seems to be resolved

**Comment by Bribabri** [comment]
Still won't load for me :(

**Comment by Bribabri** [comment]
only on mobile that is (won't load)
