### ISSUE TITLE
No Suggestion on entering pokemon name

### ISSUE THREAD

**Issue by meredori** [mksanderson/pokeswarm#5]
When entering the name of a pokemon to add or filter there is no suggestion appearing to reduce time taken to enter pokemon

**Comment by mksanderson** [comment]
Have enabled default suggestions for now (ie. Suggestion of previously entered Pokemon). Will enable suggestive search once I have confirmed design

**Comment by mksanderson** [comment]
Autocomplete is in. Test it out, let me know whatcha think

**Comment by mksanderson** [comment]
There are some missing Pokemon from the list I have, would be good to source a better list if you can find one.
