### ISSUE TITLE
blue colour

### ISSUE THREAD

**Issue by meredori** [mksanderson/pokeswarm#6]
Need an option for another colour especially at night as blue is the worst colour late at night

http://www.health.harvard.edu/staying-healthy/blue-light-has-a-dark-side

**Comment by mksanderson** [comment]
Thinking of adding a night time setting. Not sure if this should be manually or automatically activated.

I, personally, prefer dark settings all the time, so maybe:
- an optional toggle to switch between light/dark
- If you don't have a stored setting in your cache, it defaults to light between 7am - 6pm, and dark setting outside of that

Thoughts?

**Comment by Bribabri** [comment]
I was wondering why it's so dark grey now - feels too serious. Pokemon is meant to be fun right? :P

**Comment by mksanderson** [comment]
Colour is too hard. I would probably need a designers assistance for that.......

**Comment by mksanderson** [comment]
Used a darker blue than before.
