### ISSUE TITLE
Swarm data

### ISSUE THREAD

**Issue by meredori** [mksanderson/pokeswarm#9]
If possible allow me to focus on a possible swarm of pokemon (concentration of a particular pokemon in a limited area) when I do a search for a specific pokemon.

**Comment by mksanderson** [comment]
How would you imagine this working? I'm thinking we could:
- Set your map bounds to the pokemon returned by your search
- Make sure that this is pokemon you're search for "within a range -- 20km or something"

**Comment by meredori** [comment]
I would imagine that it would look for a high concentration of a pokemon in a small area. Possibly when you search/filter it would alert you to the nearest swarm and you can click to focus the map on it?
